version: "3"

services:
  python-service:
    build: .
    container_name: python-service
    expose:
      - 5000

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8011:8011"
    depends_on:
      - python-service
