pipeline {
    agent any
    environment {
        DOTNET_ROOT = '/usr/share/dotnet'
        PATH = "${env.DOTNET_ROOT}:${env.PATH}"
    }
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/你的帳號/你的repo.git'
            }
        }
        stage('Restore') {
            steps {
                sh 'dotnet restore'
            }
        }
        stage('Build') {
            steps {
                sh 'dotnet build --no-restore -c Release'
            }
        }
        stage('Test') {
            steps {
                sh 'dotnet test --no-build --verbosity normal'
            }
        }
        stage('Publish') {
            steps {
                sh 'dotnet publish -c Release -o publish'
            }
        }
    }
}
